CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uri       VARCHAR(255)                            NOT NULL,
    app       VARCHAR(50)                             NOT NULL,
    ip        VARCHAR(45)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);
